name: Build PCT frontend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install the dependencies
        run: npm ci

      - name: Audit packages
        run: npm audit

      - name: Lint codes
        run: npm run lint

      - name: Unit tests
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup git user
        run: |
          git config user.name "release-bot"

      - name: Update release branch
        run: |
          git checkout release
          git merge main
          git push
