name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/dependabot.yml'

jobs:
  test:
    uses: ./.github/workflows/test.yml
