name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/dependabot.yml'

jobs:
  test:
    if: github.actor != 'dependabot[bot]' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install the dependencies
        run: pnpm install

      - name: Audit packages
        run: pnpm audit --audit-level=high

      - name: Lint codes
        run: pnpm run lint

      - name: Unit tests
        run: pnpm run test
