name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install the dependencies
        run: pnpm install

      - name: Audit packages
        run: pnpm audit --audit-level=high

      - name: Lint codes
        run: pnpm run lint

      - name: Unit tests
        run: pnpm run test