name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install the dependencies
        run: pnpm install

      - name: Audit packages
        id: audit
        run: pnpm audit --audit-level=high
        continue-on-error: true

      - name: Lint codes
        id: lint
        run: pnpm run lint
        continue-on-error: true

      - name: Unit tests
        id: test
        run: pnpm run test
        continue-on-error: true

      - name: Check results
        if: always()
        run: |
          if [[ "${{ steps.audit.outcome }}" == "failure" || "${{ steps.lint.outcome }}" == "failure" || "${{ steps.test.outcome }}" == "failure" ]]; then
            echo "One or more steps failed:"
            echo "Audit: ${{ steps.audit.outcome }}"
            echo "Lint: ${{ steps.lint.outcome }}"
            echo "Test: ${{ steps.test.outcome }}"
            exit 1
          fi